### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by briganski** [MalwareCantFly/Vba2Graph#1]
Hi, I went to check out your tool. It is not working for me, I followed your directions correctly and several times and I am not getting the outputs your documentation reads. Looks like it is pulling the VBA out of the document ok but its not generating any graphs.

**Comment by MalwareCantFly** [comment]
Hi @briganski !
Some questions:
1. Could you provide the VBA code / hash of the malicious document?
2. What OS are you using?
3. Are you getting any errors whatsoever?

Also, please use Python 2, and not Python 3.
I'll update the README to reflect this requirement...
Thanks.

**Comment by briganski** [comment]
Hi there, sure thing, it does seem pretty weird as it seems pretty simple; 

1. I can - but I can't share it here. (briganski@gmail.com) 
2. Linux (Ubuntu 14.04.01) (Yes already using python 2.7) 
3. No errors just not seeing the images. I am using remnux it has olevba installed, modified your script based on my path (i.e telling olevba.py to execute). But that is all. 

Thanks for your help, I am probably doing something stupid hopefully )
