### ISSUE TITLE
vba2graph could use the olevba API

### ISSUE THREAD

**Issue by decalage2** [MalwareCantFly/Vba2Graph#3]
Hi, this is a great piece of work. I noticed that you run olevba as a script and then parse its console output. It may break whenever I update olevba, if the display is modified.

I would recommend to use the olevba API instead, to avoid issues in the future and to make vba2graph more robust. The API is pretty simple, and I can add more features to it if needed:

https://github.com/decalage2/oletools/wiki/olevba#how-to-use-olevba-in-python-applications

**Comment by MalwareCantFly** [comment]
Thanks a lot @decalage2 ,
I'll be travelling abroad for a few weeks..
But as soon as I'm back, I'll get right on it :)

**Comment by doomedraven** [comment]
now that is done :) so maybe instead of -i vba output you can just put file and call that new funcs which i have added ?

**Comment by MalwareCantFly** [comment]
@doomedraven I'll try to add it tomorrow, before travelling.. no promises :)

**Comment by doomedraven** [comment]
working already on it ;)

**Comment by doomedraven** [comment]
done https://github.com/MalwareCantFly/Vba2Graph/pull/4
